import {
  fuelTypeOptions,
  motorcycleTypeOptions,
  transmissionOptions,
} from '../../../../constants/selectOptions';
import {
  CUSTOM_FILE_INPUT,
  INPUT_TYPE,
  SELECT_TYPE,
  ADDRESS_INPUT,
} from '../../../../constants/types';

export const basicDataFields = [
  {
    label: 'Πινακίδα κυκλοφορίας',
    name: 'vehiclePlate',
    required: true,
    placeholder: 'Συμπληρώστε την πινακίδα',
    fieldType: INPUT_TYPE,
    maxLength: 8,
    sm: 4,
  },
  {
    label: 'Έτος κυκλοφορίας',
    name: 'vehicleYear',
    required: true,
    placeholder: 'Συμπληρώστε το έτος κυκλοφορίας',
    type: 'text',
    fieldType: INPUT_TYPE,
    onlyNumeric: true,
    maxLength: 4,
    sm: 4,
  },
  {
    label: 'Μάρκα οχήματος',
    name: 'vehicleBrand',
    required: true,
    placeholder: 'Συμπληρώστε το μοντέλο οχήματος',
    fieldType: INPUT_TYPE,
    uppercase: true,
    sm: 4,
  },
  {
    label: 'Μοντέλο οχήματος',
    name: 'vehicleModel',
    required: true,
    placeholder: 'Συμπληρώστε το μοντέλο οχήματος',
    fieldType: INPUT_TYPE,
    uppercase: true,
    sm: 4,
  },
];

export const technicalData = [
  {
    label: 'Χιλιόμετρα',
    name: 'vehicleKm',
    required: true,
    placeholder: 'Συμπληρώστε τα χιλιόμετρα',
    type: 'number',
    fieldType: INPUT_TYPE,
    sm: 4,
  },
  {
    label: 'Κυβικά',
    name: 'vehicleCc',
    required: true,
    placeholder: 'Συμπληρώστε τα κυβικά',
    type: 'number',
    fieldType: INPUT_TYPE,
    sm: 4,
  },
  {
    label: 'Ίπποι',
    name: 'vehicleHp',
    required: true,
    placeholder: 'Συμπληρώστε τους ίππους',
    type: 'number',
    fieldType: INPUT_TYPE,
    sm: 4,
  },
  {
    label: 'Τύπος Καυσίμου',
    name: 'vehicleFuelType',
    required: true,
    fieldType: SELECT_TYPE,
    options: fuelTypeOptions,
    sm: 4,
  },
  {
    label: 'Τύπος μηχανής',
    name: 'motorcycleType',
    required: true,
    fieldType: SELECT_TYPE,
    options: motorcycleTypeOptions,
    sm: 4,
  },
  {
    label: 'Σασμάν',
    name: 'vehicleTransmission',
    required: true,
    fieldType: SELECT_TYPE,
    options: transmissionOptions,
    sm: 4,
  },
];

export const documents = [
  {
    label: 'Φωτογραφίες',
    btnLabel: 'Επιλογή αρχείων',
    name: 'vehiclePhotos',
    required: false,
    type: 'file',
    multiple: true,
    fieldType: CUSTOM_FILE_INPUT,
    accept: 'image/*',
    sm: 4,
  },
  {
    label: 'Άδεια Κυκλοφορίας',
    name: 'vehicleLicence',
    required: true,
    type: 'file',
    multiple: false,
    fieldType: CUSTOM_FILE_INPUT,
    accept: 'image/*,application/pdf',
    sm: 4,
  },
  {
    label: 'Διεύθυνση',
    name: 'vehicleAddress',
    required: true,
    fieldType: ADDRESS_INPUT,
    sm: 4,
  },
];
